### ISSUE TITLE
"\xE4" on US-ASCII

### ISSUE THREAD

**Issue by xareelee** [stevenosloan/slack-notifier#29]
I ran **slack** function by **fastlane** and got the following error message (`"\xE4" on US-ASCII`):

```
/Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-1.2.0/lib/slack-notifier.rb:23:in `encode': "\xE4" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-1.2.0/lib/slack-notifier.rb:23:in `to_json'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-1.2.0/lib/slack-notifier.rb:23:in `ping'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/actions/slack.rb:57:in `run'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):159:in `block (3 levels) in parse'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/runner.rb:49:in `call'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/runner.rb:45:in `rescue in execute'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/runner.rb:8:in `execute'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/bin/fastlane:118:in `run'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.13.0/bin/fastlane:124:in `<top (required)>'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I think I didn't use a character `ä` (\xE4) for the parameter `message`. Any idea or suggestion about this?

**Comment by stevenosloan** [comment]
Hmmm, that is odd -- it *may* be related to this (https://github.com/KrauseFx/fastlane/issues/227), but maybe not. Do you think you could try w/ slack-notifier from git and see if that fixes the issue?

```ruby
gem "slack-notifier", git: "git@github.com:stevenosloan/slack-notifier.git",
                      branch: "master"
```

**Comment by xareelee** [comment]
This problem has been fixed after updating fastlane. Thanks for your help.

**Comment by stevenosloan** [comment]
No worries, glad to help.
