### ISSUE TITLE
Slack::Notifier::APIError: The slack API returned an error: action_prohibited (HTTP Code 500)

### ISSUE THREAD

**Issue by carolfly86** [stevenosloan/slack-notifier#84]
I got 500 error with simple test code. any idea what is missing?
```
notifier = Slack::Notifier.new webhook do
  defaults channel: "#test"
end
notifier.ping "Hello"
Slack::Notifier::APIError: The slack API returned an error: action_prohibited (HTTP Code 500)
Check the "Handling Errors" section on https://api.slack.com/incoming-webhooks for more information

	from /Users/xxx/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-2.2.2/lib/slack-notifier/util/http_client.rb:29:in `block in call'
	from /Users/xxx/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-2.2.2/lib/slack-notifier/util/http_client.rb:27:in `tap'
	from /Users/xxx/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-2.2.2/lib/slack-notifier/util/http_client.rb:27:in `call'
	from /Users/xxx/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-2.2.2/lib/slack-notifier/util/http_client.rb:14:in `post'
	from /Users/xxx/.rvm/gems/ruby-2.2.1@global/gems/slack-notifier-2.2.2/lib/slack-notifier.rb:47:in `post'
	from /Users/xxx/.rvm/gems/ruby-2.2.1@global/gems/slack-notifier-2.2.2/lib/slack-notifier.rb:36:in `ping'
	from (irb):63
	from /Users/xxx/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by carolfly86** [comment]
it turns out the webhookurl is invalid.
